italia/cloud.italia.it-site

- src/components/home/NewsPreview.js
- src/components/home/Strategy.js
> fix: small text

- src/components/Header.js
- src/components/home/Benefit.js
- src/components/home/Enablement.js
- src/components/home/Services.js
- src/components/home/Strategy.js
> feat: update home page

- src/components/Header.js
- src/pages/404.js
- src/pages/catalogo-servizi-cloud.js
- src/pages/index.js
- src/pages/programma-abilitazione-cloud.js
- src/pages/qualificazione-servizi-cloud.js
- src/pages/strategia-cloud-pa.js
> fix: page headings

- src/components/hero/Hero.js
> fix: mobile layout

- contents/catalogue-page/catalogue.md
- contents/catalogue-page/catalogue.yml
- src/layouts/CataloguePage.js
- src/pages/catalogo-servizi-cloud.js
> feat: catalogue page

- src/components/hero/Cta.js
- src/layouts/Layout.js
- src/layouts/home/ServicesSection.js
> fix: a11y contrast on focus

- contents/home-page/home.yml
- contents/strategy-page/strategy.yml
- src/components/hero/HeroGraphic.js
- src/layouts/IndexPage.js
- src/layouts/StrategyPage.js
- src/layouts/home/BenefitSection.js
- src/layouts/home/EnablementSection.js
- src/layouts/home/QualificationSection.js
- src/layouts/home/StrategySection.js
- src/utils/proptypes.js
> fix: alt img

- src/components/MobileSwiper.js
> fix: swiper navigation buttons

- contents/links.yml
- contents/privacy-page/privacy.md
- src/layouts/Footer.js
- src/layouts/PrivacyPolicyPage.js
- src/pages/privacy-policy.js
> feat: privacy policy page

- src/components/ExpandButton.js
- src/components/resource/ResourceReferences.js
- src/layouts/Header.js
- src/layouts/home/NewsPreviewSection.js
- src/layouts/home/QualificationSection.js
> fix svg for a11y

- contents/home-page/home.yml
> fix: a11y "link identified only by color" error

- .github/workflows/ci.yml
- pa11y.sh
- package.json
- src/components/ExpandButton.js
- src/components/resource/ResourceReferences.js
- src/layouts/Header.js
- src/layouts/home/NewsPreviewSection.js
- src/layouts/home/QualificationSection.js
- yarn.lock
> feat: add pa11y

- contents/labels.yml
- contents/seo.yml
- gatsby-config.js
- src/components/SEO.js
- src/layouts/CataloguePage.js
- src/layouts/EnablementPage.js
- src/layouts/GlossaryPage.js
- src/layouts/Header.js
- src/layouts/NotFoundPage.js
- src/layouts/PrivacyPolicyPage.js
- src/layouts/QualificationPage.js
- src/layouts/StrategyPage.js
> fix: seo info

- contents/glossary-page/glossary.yml
- contents/links.yml
- src/layouts/Footer.js
- src/layouts/GlossaryPage.js
- src/layouts/Header.js
> fix: header menu layout

- src/components/glossary/Glossary.js
- src/components/glossary/GlossaryTerm.js
- src/layouts/GlossaryPage.js
> fix: glossary page footer banner glitch

- contents/enablement-page/enablement.yml
- contents/labels.yml
- contents/qualification-page/qualification.yml
- contents/strategy-page/strategy.yml
- src/components/resource/ResourceReferences.js
- src/layouts/Header.js
- src/layouts/home/NewsPreviewSection.js
- src/layouts/home/QualificationSection.js
> fix: a11y svg

- contents/credits-page/credits.md
- contents/credits-page/credits.yml
- contents/links.yml
- contents/privacy-page/privacy.md
- src/layouts/CreditsPage.js
- src/layouts/Footer.js
- src/pages/crediti.js
> feat: credits page

- .github/workflows/cd.yml
- CONTRIBUTING.md
- package.json
> feat: gh action to deploy in prod

- contents/privacy-page/privacy.md
> feat: update privacy page

- contents/catalogue-page/catalogue.yml
- contents/enablement-page/enablement.yml
- contents/home-page/home.yml
- contents/qualification-page/qualification.yml
- contents/strategy-page/strategy.yml
- src/layouts/CataloguePage.js
- src/layouts/EnablementPage.js
- src/layouts/QualificationPage.js
> fix: alt image

- contents/privacy-page/privacy.md
> fix: wording

- contents/privacy-page/privacy.md
privacy.md was update in #143 with the new Marketplace URLs.
> chore: set update date in privacy.md

- contents/privacy-page/privacy.md
> chore(content): update privacy policy date

- contents/privacy-page/privacy.md
> chore(content): update privacy policy

- contents/notizie/2023-03-15-dal-pnrr-200-milioni-per-migrare-in-cloud-dati-e-servizi-di-asl-e-aziende-ospedaliere.md
…rvizi-di-asl-e-aziende-ospedaliere.md
> Show news in home

- contents/enablement-page/enablement.yml
Come da aggiornamento del kit su Docs Italia.
> Feat: aggiornati link kit di abilitazione con formati aperti
